In [13]:
#import torch


In [14]:
import pandas as pd

In [15]:
import numpy as np

In [16]:
def relu(x):
    return(np.maximum(x,0))
def sigmoid(x):
    return(1/(1+np.exp(-x)))
def softmax(x):
    return(np.exp(x)/sum(np.exp(x)))

In [17]:
def forwardpass(x,W1,b1,W2,b2):
    Z1 = W1.dot(x)+ b1
    A1 = relu(Z1)
    Z2 = W2.dot(A1)+b2
    A2 = softmax(Z2)
    return(Z1,A1,Z2,A2)

In [18]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [19]:
def backpass(y,x,Z1,A1,Z2,A2,w1,b1,w2,b2):
    m =  60000
    dZ2 = A2 - one_hot(y)
    dW2 = 1/m* dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    drelu= Z1>0
    dZ1 = w2.T.dot(dZ2)*drelu
    dW1 = 1/m* dZ1.dot(x.T)
    db1 = 1/m* np.sum(dZ1)
    return(dW1,db1,dW2,db2)

In [20]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions)
    print(Y)
    return np.sum(predictions == Y) / Y.size

In [21]:
def grad_desc(X,Y,alpha,num_iterations):
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    for i in range(num_iterations):
        Z1,A1,Z2,A2 = forwardpass(X,W1,b1,W2,b2)
        dW1,db1,dW2,db2 = backpass(Y,X,Z1,A1,Z2,A2,W1,b1,W2,b2)
        print(f'this is change in W2 :{dW2.shape}')
        #print(dW1,db1,dW2,db2)
        W1 -= alpha*dW1
        b1 -= alpha*db1
        W2 -= alpha*dW2
        b2 -= alpha*db2
        if i % 10 == 0:
                print("Iteration: ", i)
                predictions = get_predictions(A2)
                print(get_accuracy(predictions,Y))
    return(W1,b1,W2,b2)


In [22]:
data = pd.read_csv('./Desktop/singlecell/check/archive/mnist_train.csv')
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [23]:
W1,b1,W2,b2 = grad_desc(X_train,Y_train, 0.1, 500)

this is change in W2 :(10, 10)
Iteration:  0
[0 1 0 ... 0 0 0]
[0 6 7 ... 9 0 2]
0.10289830508474576
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
Iteration:  10
[2 3 0 ... 9 8 7]
[0 6 7 ... 9 0 2]
0.1726271186440678
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
Iteration:  20
[2 3 9 ... 9 8 7]
[0 6 7 ... 9 0 2]
0.21098305084745764
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change in W2 :(10, 10)
this is change

In [24]:
def make_predictions(X,W1,b1,W2,b2):
    Z1,A1,Z2,A2 = forwardpass(X,W1,b1,W2,b2)
    predictions = get_predictions(A2)
    return(predictions)
test_predictions = make_predictions(X_dev,W1,b1,W2,b2)
print(get_accuracy(test_predictions,Y_dev))

[0 6 4 0 1 8 9 8 4 4 3 4 3 3 8 7 4 3 9 3 5 3 9 9 8 4 6 6 6 7 1 0 1 0 7 1 4
 1 4 1 6 8 2 0 3 4 3 1 6 4 1 4 6 0 5 3 0 5 2 4 1 6 7 9 3 3 2 6 0 3 3 2 3 2
 5 0 5 8 3 4 7 1 4 7 9 1 5 4 8 0 7 6 9 3 5 9 4 1 5 1 4 0 3 9 8 9 7 4 3 3 9
 2 4 4 2 8 2 1 6 8 8 1 5 2 0 5 4 8 5 3 1 6 1 6 9 5 7 4 6 1 4 4 0 7 0 8 6 1
 4 6 9 5 1 7 7 0 9 9 3 0 4 2 7 9 9 9 8 2 1 6 9 3 9 2 5 0 1 3 3 6 4 5 8 7 1
 1 9 1 2 1 1 7 6 9 1 6 1 8 7 4 9 1 8 5 6 2 6 4 9 6 1 0 7 5 9 8 0 4 8 1 5 2
 8 0 7 6 2 0 3 1 8 5 9 1 3 3 1 9 9 0 8 1 8 9 5 8 1 8 0 8 2 4 8 9 6 3 7 1 1
 3 1 6 8 6 6 9 3 0 4 8 0 6 9 0 0 9 0 9 2 4 0 6 7 6 0 0 6 1 5 2 2 0 5 7 8 4
 7 2 0 3 2 0 6 6 1 3 5 4 2 1 6 0 0 2 4 0 3 7 3 9 5 9 2 8 7 3 9 5 0 7 1 5 6
 7 7 2 0 4 9 2 3 8 8 9 4 0 6 6 2 6 6 2 0 4 0 9 3 2 3 2 1 4 7 8 4 8 4 4 8 4
 6 4 2 9 0 5 7 7 0 1 5 4 0 0 1 2 1 1 9 7 0 1 8 7 9 8 2 6 4 5 7 5 0 9 6 8 4
 6 0 0 5 2 4 7 9 1 8 8 0 9 5 4 9 8 9 8 4 1 0 6 6 9 2 4 2 4 2 6 9 9 2 6 3 1
 9 7 0 8 6 4 7 1 0 7 6 1 2 0 5 0 1 9 0 0 5 0 7 4 7 9 6 0 1 3 2 3 9 5 6 6 0
 9 2 2 2 8 2 2 5 4 5 6 6 